<script setup lang="ts">
import { computed, ref, watch } from "vue";
import Button from "~/components/ui/Button.vue";
import { Alert, AlertDescription } from "~/components/ui/alert";
import { api } from "~/composables/useApi";

// Step 5 "Borrador" of the new-lead workspace. The draft is generated by the real
// synthesiser (POST /cases/{id}/brief) from the linked evidence; the page renders
// exactly what the backend returns — the editorial sections, the citation counts
// and the pending verifications — and never invents content. When the synthesiser
// cannot ground the central claim it abstains, and the abstention (like a
// generated draft) is what unlocks the Revisión step.
const props = withDefaults(
  defineProps<{ leadId: number; linkedIds: string[]; title: string; readonly?: boolean }>(),
  { readonly: false }
);
const emit = defineEmits<{
  (e: "back"): void;
  (e: "continue"): void;
  (e: "goEvidence"): void;
  (e: "change", payload: { draft: boolean; abstained: boolean }): void;
}>();

// Brief package as returned by the backend (tvn / banca share these keys).
interface BriefPackage {
  modalidad: string;
  abstained: boolean;
  reason?: string;
  text?: string;
  titulo_propuesto?: string;
  brief?: string;
  enfoque?: string;
  preguntas?: string;
  fuentes_y_verificaciones?: string;
  guion?: string;
  copy_digital?: string;
  titular_only?: boolean;
  citations_valid?: number;
  citations_dropped?: string[];
  missing_sources?: string[];
}

const pkg = ref<BriefPackage | null>(null);
const generating = ref(false);
const error = ref("");

const draftReady = computed(() => !!pkg.value && !pkg.value.abstained);
const abstained = computed(() => !!pkg.value?.abstained);

const sections = computed(() => {
  const p = pkg.value;
  if (!p || p.abstained) return [];
  return [
    { label: "Título propuesto", text: p.titulo_propuesto },
    { label: "Brief", text: p.brief },
    { label: "Enfoque de interés público", text: p.enfoque },
    { label: "Preguntas de investigación", text: p.preguntas },
    { label: "Fuentes y verificaciones pendientes", text: p.fuentes_y_verificaciones },
    { label: "Guion 45–60 s", text: p.guion },
    { label: "Copy digital", text: p.copy_digital },
  ].filter((s) => (s.text || "").trim());
});

const meta = computed(() => {
  const p = pkg.value;
  if (!p || p.abstained) return "";
  const dropped = p.citations_dropped?.length ?? 0;
  return `brief · ${p.citations_valid ?? 0} citas válidas${dropped ? ` · ${dropped} descartadas` : ""} · modalidad ${p.modalidad}`;
});

async function generate() {
  if (generating.value) return;
  generating.value = true;
  error.value = "";
  try {
    pkg.value = await api<BriefPackage>(`cases/${props.leadId}/brief`, {
      method: "POST",
      query: { formato: "json" },
    });
  } catch (err: any) {
    error.value = err?.data?.detail || err?.message || "No se pudo generar el borrador.";
    pkg.value = null;
  } finally {
    generating.value = false;
  }
}

watch(
  [draftReady, abstained],
  () => emit("change", { draft: draftReady.value, abstained: abstained.value }),
  { immediate: true }
);

// If the linked set changes upstream, any generated draft no longer reflects it.
watch(
  () => props.linkedIds,
  () => {
    pkg.value = null;
  },
  { deep: true }
);

const draftHead = computed(() => pkg.value?.titulo_propuesto?.trim() || props.title.trim() || "Borrador");
</script>

<template>
  <div class="flex flex-col gap-4">
    <p v-if="error" class="text-body-sm text-destructive">{{ error }}</p>

    <!-- Idle · nothing generated yet -->
    <template v-if="!pkg && !generating">
      <div v-if="readonly" class="rounded-md bg-surface-sunken px-4 py-3 text-body-sm text-ink-muted">
        El borrador se genera en el flujo de trabajo del lead.
      </div>
      <template v-else>
        <div class="flex flex-col gap-2 rounded-md bg-surface-sunken p-4">
          <span class="text-label uppercase text-ink-muted">
            Se usarán {{ linkedIds.length }} fuentes vinculadas
          </span>
          <div class="flex flex-wrap gap-1.5">
            <span
              v-for="id in linkedIds"
              :key="id"
              class="rounded-sm bg-surface px-1 font-mono text-caption text-ink-muted"
            >
              {{ id }}
            </span>
          </div>
        </div>
      </template>
    </template>

    <!-- Generating -->
    <div
      v-else-if="generating"
      class="flex flex-col gap-2 rounded-md border border-border bg-canvas p-6 text-center"
    >
      <span class="font-serif text-heading-md text-ink">Generando borrador…</span>
      <span class="text-body-sm text-ink-muted">
        El sintetizador redacta solo con la evidencia vinculada. Puede tardar unos segundos.
      </span>
    </div>

    <!-- Abstention · backend could not ground the claim -->
    <div
      v-else-if="abstained"
      class="flex flex-col gap-3 rounded-md border-[1.5px] border-destructive bg-destructive/5 p-6"
    >
      <div class="flex flex-wrap items-center justify-between gap-3">
        <h3 class="font-serif text-heading-md leading-tight">Abstención</h3>
        <span class="font-mono text-caption text-ink-muted">modalidad {{ pkg?.modalidad }}</span>
      </div>
      <p class="text-pretty text-body-sm leading-relaxed text-ink">
        {{ pkg?.reason || pkg?.text || "El sintetizador no generó un borrador con la evidencia vinculada." }}
      </p>
      <p class="text-body-sm font-semibold text-success">Ninguna cifra o cita fue inventada.</p>
      <div v-if="!readonly" class="flex flex-wrap gap-2">
        <Button variant="outline" @click="emit('goEvidence')">← Vincular más evidencia</Button>
        <Button variant="outline" @click="generate">↻ Reintentar</Button>
      </div>
    </div>

    <!-- Draft -->
    <template v-else-if="draftReady">
      <Alert v-if="pkg?.titular_only" variant="warning">
        <AlertDescription class="text-body-sm leading-relaxed text-ink">
          <strong class="font-semibold text-warning">Aviso:</strong>
          el borrador se basa únicamente en titulares/metadatos.
        </AlertDescription>
      </Alert>

      <article class="flex flex-col gap-4 rounded-md border border-border p-6">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <span class="text-caption font-semibold uppercase tracking-[0.6px] text-ink-muted">
            Borrador · no publicado
          </span>
          <span class="font-mono text-caption text-ink-muted">{{ meta }}</span>
        </div>
        <h3 class="text-balance font-serif text-display-lg leading-tight">{{ draftHead }}</h3>

        <div v-for="s in sections" :key="s.label" class="flex flex-col gap-1">
          <span class="text-label uppercase text-ink-muted">{{ s.label }}</span>
          <p class="text-pretty text-body-md leading-relaxed text-ink" style="white-space: pre-line">{{ s.text }}</p>
        </div>

        <div
          v-if="pkg?.missing_sources?.length"
          class="flex flex-col gap-1.5 border-t border-border pt-3"
        >
          <span class="text-label uppercase text-warning">Qué falta · fuentes sin resolver</span>
          <p v-for="m in pkg.missing_sources" :key="m" class="font-mono text-caption text-warning">
            {{ m }}
          </p>
        </div>
      </article>

      <div v-if="!readonly" class="flex flex-wrap gap-2">
        <Button variant="outline" class="h-9 text-caption font-semibold" @click="generate">↻ Regenerar</Button>
      </div>
    </template>

    <!-- Footer nav -->
    <div v-if="!readonly" class="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4">
      <Button variant="outline" @click="emit('back')">← Atrás</Button>
      <Button v-if="draftReady || abstained" @click="emit('continue')">Continuar · Revisión →</Button>
      <Button v-else :disabled="generating" @click="generate">
        {{ generating ? "Generando…" : "Generar borrador" }}
      </Button>
    </div>
  </div>
</template>
